package grafica;

import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.EtchedBorder;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;

import controle.Pokemon;

import poo.Mensagem;

import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Elton e Flavia<br>
 * <p>
 * Classe que contem a tela principal de batalha, é onde ocorre a batalha em si.
 * </p>
 */
public class Batalha extends javax.swing.JPanel {

    /**
     * Creates new form Batalha
     */
     
   
    JPanel selecao;
    TelaPrincipal tela;
    String[][] vetPoke;
	public Pokemon[] Pokemons;//vetor de pokemons que armazena os pokemons do jogador
   
    /**
     * Construtor da classe
     * @param t Objeto do tipo TelaPrincipal, component principal do jogo.
     * @param p Objeto do tipo Selecao.
     */
    public Batalha(TelaPrincipal t, JPanel p){
         initComponents();
         this.tela=t;
         this.selecao=p;
         tela.b=false;
     }
    /**
     * @wbp.parser.constructor
     */
    /**
     * 
     * @param t Objeto do tipo TelaPrincipal, component principal do jogo.
     * @param p Objeto do tipo Selecao.
     * @param msg String que contem todas as mensagens trocadas ate agora para manter a conversa na janela de chat
     */
    public Batalha(TelaPrincipal t, JPanel p,String msg){
        initComponents();
        this.tela=t;
        this.selecao=p;
        this.jTAChat.append(msg);
        tela.b=false;
    }
    /**
     * 
     * @param t Objeto do tipo TelaPrincipal, component principal do jogo.
     * @param p Objeto do tipo Selecao.
     * @param msg String que contem todas as mensagens trocadas ate agora para manter a conversa na janela de chat
     * @param vetPoke Vetor com os pokemons foram escolhidos e informacoes das imagens a serem utilizadas
     */
    public Batalha(TelaPrincipal tela2, Selecao selecao, String mensagens,
			String[][] vetPoke) {
    	initComponents();
        this.tela=tela2;
        this.selecao=selecao;
        this.jTAChat.append(mensagens);
        this.vetPoke=vetPoke;
        tela.b=false;
        this.Pokemons=new Pokemon[6];
        this.Pokemons[0]=new Pokemon(Integer.parseInt(vetPoke[0][3]));
        this.Pokemons[1]=new Pokemon(Integer.parseInt(vetPoke[1][3]));
        this.Pokemons[2]=new Pokemon(Integer.parseInt(vetPoke[2][3]));
        this.Pokemons[3]=new Pokemon(Integer.parseInt(vetPoke[3][3]));
        this.Pokemons[4]=new Pokemon(Integer.parseInt(vetPoke[4][3]));
        this.Pokemons[5]=new Pokemon(Integer.parseInt(vetPoke[5][3]));
        jPBBarradeVida.setValue(Pokemons[0].getVida());
        jLPokemonEscolhido.setIcon(new javax.swing.ImageIcon(getClass().getResource(vetPoke[0][2])));
        
        jLPokemonAdversario.setIcon(new javax.swing.ImageIcon(getClass().getResource(setIconAdver(tela.getListaPokemons().split(":")[6].split("=")[0]))));
        
    }
    /*
     * Atualiza a imagem do pokemon do adversario com a imagem recebida do servidor
     */
	private String setIconAdver(String string) {
		switch(Integer.parseInt(string)){
		case 0: return "/Imagens/ponytaG.png";
		case 1: return "/Imagens/shellderG.png";
		case 2: return "/Imagens/bulbasaurG.png";
		case 3: return "/Imagens/goldeenG.png";
		case 4: return "/Imagens/geodudeG.png";
		case 5: return "/Imagens/hoothootG.png";
		case 6: return "/Imagens/caterpieG.png";
		case 7: return "/Imagens/sandshrewG.png";
		case 8: return "/Imagens/pikachuG.png";
		case 9: return "/Imagens/mankeyG.png";			
		}
		return null;
	}
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jBTrocarPokemon = new javax.swing.JButton();
        jBItem = new javax.swing.JButton();
        jBAtacar = new javax.swing.JButton();

        jButton1.setText("jButton1");
        
        jLPokemonAdversario = new JLabel("");
        jLPokemonAdversario.setBackground(Color.LIGHT_GRAY);
        jLPokemonAdversario.setIcon(new ImageIcon(Batalha.class.getResource("/Imagens/caterpieG.png")));
        
        jPBVidaPokeonAdversario = new JProgressBar();
        jPBVidaPokeonAdversario.setForeground(new Color(0, 128, 0));
        jPBVidaPokeonAdversario.setToolTipText("Vida");
        jPBVidaPokeonAdversario.setValue(100);
        jPBVidaPokeonAdversario.setStringPainted(true);
        
        jPBBarradeVida = new JProgressBar();
        jPBBarradeVida.setValue(100);
        jPBBarradeVida.setToolTipText("Vida");
        jPBBarradeVida.setStringPainted(true);
        jPBBarradeVida.setForeground(new Color(0, 128, 0));
        
        jLPokemonEscolhido = new JLabel("");
        jLPokemonEscolhido.setBackground(Color.LIGHT_GRAY);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(322, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jPBVidaPokeonAdversario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addComponent(jLPokemonAdversario, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 173, GroupLayout.PREFERRED_SIZE)))
        		.addGroup(Alignment.LEADING, jPanel1Layout.createSequentialGroup()
        			.addGap(11)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPBBarradeVida, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLPokemonEscolhido, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(336, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(8)
        			.addComponent(jLPokemonAdversario, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPBVidaPokeonAdversario, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
        			.addComponent(jLPokemonEscolhido, GroupLayout.PREFERRED_SIZE, 84, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPBBarradeVida, GroupLayout.PREFERRED_SIZE, 20, GroupLayout.PREFERRED_SIZE)
        			.addGap(4))
        );
        jPanel1.setLayout(jPanel1Layout);

        jBTrocarPokemon.setText("Trocar Pokémon");
        jBTrocarPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTrocarPokemonActionPerformed(evt);
            }
        });

        jBItem.setText("Usar Item");
        jBItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBItemActionPerformed(evt);
            }
        });

        jBAtacar.setText("Atacar");
        jBAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtacarActionPerformed(evt);
            }
        });
        
        JButton jBSair = new JButton("Sair");
        jBSair.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		sair(e);
        	}
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jBAtacar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jBTrocarPokemon, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jBItem, GroupLayout.PREFERRED_SIZE, 148, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jBSair, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jBAtacar)
        				.addComponent(jBItem))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jBTrocarPokemon)
        				.addComponent(jBSair))
        			.addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel6.setLayout(jPanel6Layout);
        
        JPanel jPChat = new JPanel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel6, GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
        					.addGap(69))
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addComponent(jPChat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addGap(2))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING, false)
        				.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        				.addComponent(jPChat, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        			.addPreferredGap(ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
        			.addComponent(jPanel6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(23, Short.MAX_VALUE))
        );
        
        panel_1 = new JPanel();
        panel_1.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        jPChat.add(panel_1);
        
        panel_2 = new JPanel();
        panel_2.setLayout(null);
        panel_2.setBorder(new EtchedBorder(EtchedBorder.RAISED, null, null));
        
        jTFchat = new JTextField();
        jTFchat.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		JBEnviarChatActionPerformed(e);
        	}
        });
        jTFchat.setColumns(10);
        jTFchat.setBounds(0, 12, 120, 32);
        panel_2.add(jTFchat);
        
        btnEnviar = new JButton("Enviar");
        btnEnviar.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		JBEnviarChatActionPerformed(e);
        	}
        });
        btnEnviar.setBounds(119, 15, 77, 25);
        panel_2.add(btnEnviar);
        
        scrollPane = new JScrollPane();
        GroupLayout gl_panel_1 = new GroupLayout(panel_1);
        gl_panel_1.setHorizontalGroup(
        	gl_panel_1.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 222, Short.MAX_VALUE)
        		.addComponent(panel_2, Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        		.addComponent(scrollPane, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
        );
        gl_panel_1.setVerticalGroup(
        	gl_panel_1.createParallelGroup(Alignment.TRAILING)
        		.addGap(0, 334, Short.MAX_VALUE)
        		.addGroup(gl_panel_1.createSequentialGroup()
        			.addComponent(scrollPane, GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(panel_2, GroupLayout.PREFERRED_SIZE, 56, GroupLayout.PREFERRED_SIZE))
        );
        
        jTAChat = new JTextArea();
        jTAChat.setEditable(false);
        scrollPane.setViewportView(jTAChat);
        panel_1.setLayout(gl_panel_1);
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Função que altera o panel inferior de opcoes para o opcao desejada.
     * Ex: itens,atacar,troca pokemon
     * @param panel panel a ser substituido
     */
   public void  colocarPanel(JPanel panel){  
  jPanel6.removeAll();  
      javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);  
        jPanel6.setLayout(jPanel6Layout);  
        jPanel6Layout.setHorizontalGroup(  
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  
        );  
        jPanel6Layout.setVerticalGroup(  
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  
        );  
}
    
    /*
     * evento do botão atacar
     */
    private void jBAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtacarActionPerformed
        
        colocarPanel(new Atacar(tela,selecao,this));
       
    }//GEN-LAST:event_jBAtacarActionPerformed
    /*
     * evento do botão itens
     */
    private void jBItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBItemActionPerformed
        // TODO add your handling code here:
           colocarPanel(new Itens(tela, selecao,this));
    }//GEN-LAST:event_jBItemActionPerformed
    /*
     * evento do botão trocar
     */
    private void jBTrocarPokemonActionPerformed(java.awt.event.ActionEvent evt) {
    	TrocaPokemon t=new TrocaPokemon(this);
    	t.setBounds(0,0,this.getWidth(),this.getHeight());
    	t.setVisible(true);
    	tela.setContentPane(t);
    }//GEN-LAST:event_jBTrocarPokemonActionPerformed

    /*
     *evento do botão enviar, é chamado quando se deseja enviar uma mensagem de texto. Ele atualiza a tela do usuario e manda a 
     *mensagem para o servidor
     */
    private void JBEnviarChatActionPerformed(ActionEvent e){
        
    	jTAChat.append("eu: " + jTFchat.getText() + "\n");

        Mensagem m = new Mensagem(110,jTFchat.getText());
        tela.cliente.enviaMensagem(m);
        
        jTFchat.setText("");


    }
    /**
     * Escreve a mensagem de chat recebida na tela do usuario.Ela adiciona o nome do cliente antes da mensagem.
     * O nome do cliente foi armazenado quando os dois clientes se conectam, o servidor manda uma mensagem para cada cliente com o nome do jogador
     * adversário.
     * @param s Mensagem recebida
     */
    public void escreveChat(String s){
    	if(tela.nomeAdversario.isEmpty()){
    		jTAChat.append(s+"\n");
    	}else{
    	jTAChat.append(tela.nomeAdversario+" : "+s+"\n");
    	}
    }
    /**
     * Funcao que e chamada quando o botao sair e acionado, recebe como parametro um Action Event
     * @param e ActionEvent
     */
    public void sair(ActionEvent e){
    	Sair s = new Sair(tela);
    	s.setVisible(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtacar;
    private javax.swing.JButton jBItem;
    private javax.swing.JButton jBTrocarPokemon;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel6;
    private JPanel panel_1;
    private JPanel panel_2;
    private JTextField jTFchat;
    private JButton btnEnviar;
    private JScrollPane scrollPane;
    private JTextArea jTAChat;
    public JLabel jLPokemonEscolhido;
    private JLabel jLPokemonAdversario;
    public JProgressBar jPBBarradeVida;
    private JProgressBar jPBVidaPokeonAdversario;
    
    /*
     * Funcao que retonar a label que é a imagem do pokemon da arena do jogador...
     * 
     */
    protected JLabel getJLPokemonEscolhido(){
    	return this.jLPokemonEscolhido;
    }
	/**
	 * Funcao que e acionada para processar as informacoes de final de rodada, atualiza a vida dos pokemons.
	 * @param m Mensagem de atualizacao de rodada enviado pelo servidor.
	 */
    public void rodada(Mensagem m){
    	Pokemons[0].setVida(Integer.parseInt(m.corpo.split(":")[1].split("=")[1]));
    	jPBBarradeVida.setValue(Pokemons[0].getVida());
    	if(Pokemons[0].getVida()==0){
    		jBTrocarPokemonActionPerformed(null);
    	}
    	
    	jPBVidaPokeonAdversario.setValue(Integer.parseInt(m.corpo.split(":")[2].split("=")[1]));
    	jLPokemonAdversario.setIcon(new javax.swing.ImageIcon(getClass().getResource(this.setIconAdver(m.corpo.split(":")[2].split("=")[0]))));
    }
}
