package grafica;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hospedagem.java
 *
 * Created on 18/11/2013, 09:11:04
 */
/**
 *
 * @author	Elton e Flavia<br>
 * <p>
 * Classe que faz a TelaPrincipal ter uma imagem de fundo
 * </p>
 */
public class Hospedagem extends javax.swing.JPanel {

    private Image fundo;
    /** Creates new form Hospedagem */
    /**
     * Construtor que seta a imagem de fundo para a tela inicial
     */
    public Hospedagem() {
        initComponents();
        fundo = new ImageIcon(this.getClass().getResource("/Imagens/fundo.jpg")).getImage();
    
    }
    /**
     * Construtor que seta a imagem de fundo para a tela inicial,recebendo o caminho da imagem como parametro
     * @param img Caminho da imagem a ser botada como fundo
     */
    public Hospedagem(String img) {
        initComponents();
        fundo = new ImageIcon(this.getClass().getResource(img)).getImage();
    
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        if(fundo != null){
            g.drawImage(fundo, 0, 0, getWidth(), getHeight() ,this);
        }    
    }
        

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLHost = new javax.swing.JLabel();
        jLNameHost = new javax.swing.JLabel();
        jTNameHost1 = new javax.swing.JTextField();
        jBOkHost = new javax.swing.JButton();

        jLHost.setFont(new java.awt.Font("Dialog", 0, 48));
        jLHost.setForeground(new java.awt.Color(-65536,true));
        jLHost.setText("Host");

        jLNameHost.setFont(new java.awt.Font("Dialog", 0, 24));
        jLNameHost.setText("Nome:");

        jTNameHost1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNameHost1ActionPerformed(evt);
            }
        });

        jBOkHost.setText("Ok");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLHost))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLNameHost)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBOkHost, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTNameHost1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLHost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(jBOkHost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLNameHost)
                    .addComponent(jTNameHost1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void jTNameHost1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNameHost1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTNameHost1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOkHost;
    private javax.swing.JLabel jLHost;
    private javax.swing.JLabel jLNameHost;
    private javax.swing.JTextField jTNameHost1;
    // End of variables declaration//GEN-END:variables
}
