package grafica;

import javax.swing.JPanel;

import poo.Mensagem;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Função que e chamada quando o enter e pressionado no campo de texto<br>
 * <p> Janela que contem as opcoes de itens a serem escolhidos.</p>
 */
public class Itens extends javax.swing.JPanel {

    /**
     * Creates new form Itens
     */
    JPanel selecao;
    TelaPrincipal tela;
    Batalha b;
    /**
     * 
     * @param t Classe TelaPrincipal do programa
     * @param p Panel Selecao sendo utilizado
     * @param b Panel Batalha sendo utilizado
     */
    public Itens(TelaPrincipal t, JPanel p,Batalha b) {
        initComponents();
        this.tela=t;
        this.selecao=p;
        this.b=b;
    }
    /**
     * Funcao responsavel por voltar para a tela de batalha
     * @param panel Panel Batalha
     */
    public void  colocarPanel(JPanel panel){  
  jPanel1.removeAll();  
      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);  
        jPanel1.setLayout(jPanel1Layout);  
        jPanel1Layout.setHorizontalGroup(  
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  
        );  
        jPanel1Layout.setVerticalGroup(  
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)  
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)  
        );  
} 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBHealer = new javax.swing.JButton();
        jBPocao = new javax.swing.JButton();

        jBHealer.setText("Curador");
        jBHealer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBHealerActionPerformed(evt);
            }
        });

        jBPocao.setText("Poção");
        jBPocao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPocaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBHealer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBPocao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBHealer)
                    .addComponent(jBPocao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    /*
     * Função que é chamada quando o botão Healer é acionado
     */
    private void jBHealerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBHealerActionPerformed
        // TODO add your handling code here:
        colocarPanel(new BatalhaOpcoes(tela,selecao,b));
        tela.cliente.enviaMensagem(new Mensagem(320,null));
        
    }//GEN-LAST:event_jBHealerActionPerformed
    /*
     * Função que é chamada quando o botão Poção é acionado
     */
    private void jBPocaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPocaoActionPerformed
        // TODO add your handling code here:
        colocarPanel(new BatalhaOpcoes(tela, selecao,b));
        tela.cliente.enviaMensagem(new Mensagem(321,null));
    }//GEN-LAST:event_jBPocaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBHealer;
    private javax.swing.JButton jBPocao;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
