package grafica;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Hospedagem.java
 *
 * Created on 18/11/2013, 09:11:04
 */
/**
 *
 * @author Elton e Flavia<br>
 *<p>
 *Classe complementar utilizada para fazer a tela inicial ter uma imagem de fundo
 *</p>
 */
public class Tela extends javax.swing.JPanel {

    private Image fundo;
    /** Creates new form Hospedagem */
    /**
     * Construtor para configurar a imagem do fundo da TelaPrincipal
     */
    public Tela() {
        initComponents();
        fundo = new ImageIcon(this.getClass().getResource("/Imagens/fundo.jpg")).getImage();
    
    }
    /**
     * Construtor para configurar a imagem do fundo da TelaPrincipal
     * @param img Caminho da imagem que vai ser botada como plano de fundo na TelaPrincipal
     */
    public Tela(String img) {
        initComponents();
        fundo = new ImageIcon(this.getClass().getResource(img)).getImage();
    
    }
    
    @Override
   protected void paintComponent(Graphics g) {  
        super.paintComponent(g);  
        g.drawImage(fundo, 0, 0, getWidth(), getHeight(), this);  
    }  

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
